Text Size
duckduckgo/iOS pull request #1008
Opened 2021-11-23 11:07 UTC by miasma13

Task/Issue URL: https://app.asana.com/0/414235014887631/1201006464305307/f
Tech Design URL: https://app.asana.com/0/481882893211075/1201068474798176/f
CC:

**Description**:
Addition of text size setting that enables to adjust text size on browsed web pages.

**Steps to test this PR**:
1. Open Settings
2. Select "Text Size" in "Customize" section
3. Use the slider to adjust the text to preferred size 

<br/>
<div>
<img src="https://user-images.githubusercontent.com/2386389/143012296-81f81718-cb16-4d95-9e56-118924dba317.png" width=30% height=30%>
<img src="https://user-images.githubusercontent.com/2386389/143012304-81d41b52-96d0-47a6-ae68-97b31f19901b.png" width=30% height=30%>
<img src="https://user-images.githubusercontent.com/2386389/143012307-8a3e644c-98cb-49cd-b0ef-e7cfb666fab6.png" width=30% height=30%>
</div>

<br/>

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone
* [ ] iPad

**OS Testing**:

* [ ] iOS 13
* [ ] iOS 14
* [ ] iOS 15

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

2021-12-01 13:05 UTC, brindy approved these changes
Really great work, well done.  As discussed please get someone to have a look over the JavaScript (@SlayterDev or @jonathanKingston  if they have time) and once they give you a 👍  go ahead and merge.

2021-12-01 14:29 UTC, SlayterDev requested changes
This is looking good functionally. To stay in line with our JS standards there are some changes to be made. I'll reach out to discuss further.

2021-12-01 14:29 UTC, SlayterDev commented on Core/TextSizeUserScript.swift
> +        (function() {
This is a very large piece of JS to inline in the Swift code. It would be far more preferable to break this into a separate JS file and load it via `loadJS` as in some of our other user scripts. The main benefits being it will be easier to maintain/troubleshoot additionally it will be linted as JavaScript.

2021-12-01 14:29 UTC, SlayterDev commented on Core/TextSizeUserScript.swift
> +            document.adjustTextSize = adjustTextSize;
We prefer to avoid attaching globals to `document`, `window`, and `navigator` objects. This could allow scripts on the page to adjust the font size without the user's knowledge or to remove our handler all together.

An alternate solution is to inject the needed code each time (as in line 159) rather than attaching to document. I'll sync up with you to discuss this more.

2021-12-01 14:29 UTC, SlayterDev commented on Core/TextSizeUserScript.swift
> +                    StaticCounter.count++;
Could we get a brief comment for why the counter is necessary?

2021-12-01 14:29 UTC, SlayterDev commented on Core/TextSizeUserScript.swift
> +    public weak var delegate: PrintingUserScriptDelegate?
Why are we using `PrintingUserScriptDelegate` here?

2021-12-01 14:29 UTC, SlayterDev commented on Core/TextSizeUserScript.swift
> +            let shouldAdjustForDynamicType = topLevelUrl.hostname.endsWith("wikipedia.org");
Do we ever expect to have more domains to need this? Would be nice to manage this more as a dynamic list. Similar to how exceptions are injecting into the fingerprinting script.

2021-12-01 14:29 UTC, SlayterDev commented on Core/TextSizeUserScript.swift
> +            let isDDG = topLevelUrl.hostname.endsWith("duckduckgo.com");
this would be true for `notduckduckgo.com`

2021-12-02 20:51 UTC, SlayterDev approved these changes
Looks and runs great. Thank you for these changes @miasma13! 👍

2021-12-03 13:51 UTC, merged

2021-12-30 15:55 UTC, jonathanKingston commented
> As discussed please get someone to have a look over the JavaScript (@SlayterDev or @jonathanKingston if they have time) and once they give you a 👍 go ahead and merge.

Sorry I'm always missing GH notifications (If you ever need me Asana is a better bet).

I raised a issue: https://app.asana.com/0/1200890834746050/1201594810931832/f to discuss making this remotely configurable. Also the linting PR made some changes to the JS too: https://github.com/duckduckgo/iOS/pull/997