Move bookmark folders plural to stringsdict
duckduckgo/iOS pull request #1059
Opened 2022-02-16 19:07 UTC by THISISDINOSAUR

Task/Issue URL:
Tech Design URL:
CC:

**Description**:
Just some clean up

**Steps to test this PR**:
1. Test deleting a bookmarks folder with 1 item and the text is correct
2. Test deleting a bookmarks folder with 2 or more items and the text is correct
3. Repeat the above in other languages
4. Test other plurals haven't been messed up (e.g. trackers blocked dax dialog in onboarding (e.g. go through initial onboarding and then to cnn.com to get the dax dialog with multiple trackers))

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPad

**OS Testing**:

* [ ] iOS 13
* [ ] iOS 14
* [ ] iOS 15

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

2022-02-23 16:11 UTC, amddg44 reviewed
In terms of the bookmark folder deletion messages, I tested in a few different languages and looks good 👍 

A few small issues have crept into some of the translations of `dax.onboarding.browsing.multiple.trackers` though!

- DE: all line breaks are gone
- CS: one of the line breaks has been replaced by html linebreak tags
- SK: line breaks replaced by html linebreak tags and most of the message is now in bold

<img width="252" alt="image" src="https://user-images.githubusercontent.com/91189922/155358042-56a636a8-8f55-4392-9aed-155ae9f25fe2.png"> <img width="252" alt="image" src="https://user-images.githubusercontent.com/91189922/155358096-13518cbc-f356-483c-8301-1c3dec8a7bc8.png"> <img width="252" alt="image" src="https://user-images.githubusercontent.com/91189922/155358073-a849b398-55e3-4a01-bf7e-f004126903e6.png">

2022-02-24 14:34 UTC, THISISDINOSAUR commented
Thanks a lot for reviewing! I'd fixed this in one language, but didn't realise it'd happen so broadly. I'll have to fix it on Smartling I think

2022-02-24 14:35 UTC, THISISDINOSAUR commented
CS uses a mix of correct and incorrect line breaks 😂 
![Screenshot 2022-02-24 at 14 35 17](https://user-images.githubusercontent.com/1093508/155544640-bbdeb5ca-4a42-4da6-88dc-eadd206fc1d4.png)

2022-02-24 15:13 UTC, THISISDINOSAUR commented
This should be fixed now

2022-02-24 16:03 UTC, amddg44 requested changes
Looking good! Just a tweak to SK needed to correctly attribute text 👍

2022-02-24 16:03 UTC, amddg44 commented on DuckDuckGo/sk.lproj/Localizable.stringsdict
> +			<string>*%2$@, %3$@* a *%1$d ďalší sa vás tu pokúsili sledovať.
The closing `*` has been lost here so most of the message is bolded

<img width="402" alt="image" src="https://user-images.githubusercontent.com/91189922/155558042-55ea2264-91ad-4cde-88f2-807646ac1f85.png">

2022-02-24 16:03 UTC, amddg44 commented on DuckDuckGo/sk.lproj/Localizable.stringsdict
> +			<string>*%2$@, %3$@* a *%1$d ďalší sa vás tu pokúsili sledovať.
Missing `*` here too

2022-02-24 16:03 UTC, amddg44 commented on DuckDuckGo/sk.lproj/Localizable.stringsdict
> +			<string>*%2$@, %3$@* a *%1$d ďalší sa vás tu pokúsili sledovať.
And final missing one!

2022-02-24 18:29 UTC, THISISDINOSAUR commented
Sorry about that! I missed the bold when I was checking it. We might need to do something to stop this happening again in the future, since we can't check every string for every language when it's xliffs. I'm not sure what though

2022-02-25 06:22 UTC, amddg44 approved these changes
No worries, it was easy to miss! And agree that we will need to start discussing a better long term strategy here at some point soon

2022-02-25 11:46 UTC, merged