Use config to determine if UA should be omitted
duckduckgo/iOS pull request #1142
Opened 2022-05-04 15:35 UTC by SlayterDev

Task/Issue URL: https://app.asana.com/0/1200890834746050/1200932417493197/f
Tech Design URL:
CC: @brindy 

**Description**:
This PR uses the config to see if the custom UserAgent should be omitted

**Tagging instructions**
If this PR isn't ready to be merged for whatever reason it should be marked with the `DO NOT MERGE` label (particularly if it's a draft)
If it's pending Product Review/PFR, please add the `Pending Product Review` label.

If at any point it isn't actively being worked on/ready for review/otherwise moving forward (besides the above PR/PFR exception) strongly consider closing it (or not opening it in the first place). If you decide not to close it, make sure it's labelled to make it clear the PRs state and comment with more information.

**Steps to test this PR**:
1. See https://github.com/duckduckgo/BrowserServicesKit/pull/95

**Device Testing**:

* [x] iPhone SE (1st Gen)
* [x] iPhone 8
* [x] iPhone X
* [x] iPad

**OS Testing**:

* [x] iOS 13
* [x] iOS 14
* [x] iOS 15

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

2022-05-05 14:20 UTC, brindy approved these changes
LGTM! Feel free to merge once the config and BSK changes have been merged.

2022-05-05 14:22 UTC, brindy requested changes
Actually - there are test failures that look related. :)

2022-05-06 10:39 UTC, brindy approved these changes
Nice work. You have conflicts now 🙃  - but feel free to merge once they're resolved :)

2022-05-23 18:31 UTC, SlayterDev commented on DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +          "version": "7.2.2"
This was unintentional. Let me know and I can revert if needed.

2022-05-25 09:37 UTC, brindy approved these changes
LGTM, get it in :)

2022-05-25 19:41 UTC, merged