Fix for widget not showing favorites when favicons are too large
duckduckgo/iOS pull request #1183
Opened 2022-06-08 15:44 UTC by amddg44

Task/Issue URL: https://app.asana.com/0/414709148257752/1202381793018418
Tech Design URL:
CC:

**Description**:
Widget not showing favorites when favicons are too large. This fix: 
- Downsizes all existing large favicons to a max size of 192x192 as a one off migration 
- Downsizes large favicons before they are saved / cached 

**Steps to test this PR**:
1. Install the app on simulator or device from last release and add twitter.com as a favorite. Add widget to your home screen and confirm the favicons are not loading in the widget. Also confirm in Debug > Image Cache that the bookmark cache image for twitter.com is 1024x1024
2. Install the app on the same simulator or device from this branch / PR and launch the app
3. Confirm in Debug > Image Cache that the bookmark cache image for twitter.com is now 192x192
4. Minimise the app and confirm that the widget now displays favicons
5. Visit si.com (which has a 512x512 favicon) in browser and add to favorites. 
6. Confirm in Debug > Image Cache that its favicon size in both bookmarks and tabs caches is 192x192

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

2022-06-09 15:55 UTC, jaceklyp commented
Actually when running the app on develop I can't reproduce the part:
"Add widget to your home screen and confirm the favicons are not loading in the widget"
am I missing something?

2022-06-09 15:55 UTC, jaceklyp requested changes

2022-06-09 15:55 UTC, jaceklyp commented on Core/UserDefaultsPropertyWrapper.swift
> +		case faviconSizeNeedsMigration = "com.duckduckgo.ios.favicons.sizeNeedsMigration"
something's wrong with the indentation

2022-06-09 15:55 UTC, jaceklyp commented on DuckDuckGo/Favicons.swift
> +    public func migrateFaviconsWith(size: CGSize, afterMigrationHandler: @escaping () -> Void) {
it should be migrateFavicons(with size: or perhaps migrateFavicons(to size:

2022-06-09 15:55 UTC, jaceklyp commented on DuckDuckGo/Favicons.swift
> +    func isValidImage(_ image: UIImage, forMaxSize size: CGSize) -> Bool {
private

2022-06-09 15:55 UTC, jaceklyp commented on DuckDuckGo/Favicons.swift
> +    func resizeImage(_ image: UIImage, toSize size: CGSize) -> UIImage {
private

2022-06-09 15:55 UTC, jaceklyp commented on DuckDuckGo/Favicons.swift
> +    func isValidImage(_ image: UIImage, forMaxSize size: CGSize) -> Bool {
my personal taste would be to create a private extension on UIImage with method:
func isValid(for size: CGSize) -> Bool
but it's up to you :)

2022-06-09 15:55 UTC, jaceklyp commented on DuckDuckGo/Favicons.swift
> +    func resizeImage(_ image: UIImage, toSize size: CGSize) -> UIImage {
same comment as above (private extension on UImage)
func resized(to size: CGSize) -> UImage (notice "d" as it returns the UIImage and doesn't mutate the existing one)
[in the same manner as sort() is mutating and sorted() is non mutating func on array]

2022-06-09 16:03 UTC, amddg44 commented
> Actually when running the app on develop I can't reproduce the part:
> "Add widget to your home screen and confirm the favicons are not loading in the widget"
> am I missing something?

Can you confirm that you have twitter.com added as a top favorite and that the favicon for it is 1024 x 1024 (you can check this in the Debug > Image Cache screen)

2022-06-10 05:52 UTC, jaceklyp commented
tested on the device and it works, lgtm!

2022-06-10 05:55 UTC, jaceklyp approved these changes

2022-06-10 06:05 UTC, merged