Fixed minor misspelled words in the swift comments & Class name
duckduckgo/iOS pull request #1261
Opened 2022-07-31 10:30 UTC by byaruhaf

Task/Issue URL: #1260
Tech Design URL:
CC:

**Description**:

This PR corrects a few minor misspelled words in the swift comments & Class name.

Example class:
```swift
class OnboardingDefaultBroswerViewController: OnboardingContentViewController {}
```
corrected to
```swift
class OnboardDefaultBrowserViewController: OnboardingContentViewController {}
```

Example comments:
```swift
        // Make sure muliline labels are correctly presented
```
corrected to 
```swift
        // Make sure multiline labels are correctly presented
```

In addition, this PR adjusts the expectation wait timeout, for the test  ```testWhenRequestIsMadeThenHasNavParameter``` by 1 second to correct the failing test. Is it acceptable to bump some of these timeouts within the scope of this PR?

2022-08-03 19:49 UTC, samsymons requested changes
@byaruhaf Thanks so much for this! I spotted one thing to change, but otherwise this looks good.

By the way: we have a code freeze for the next couple weeks, so I've created a reminder task internally to merge this once that is over.

2022-08-03 19:49 UTC, samsymons commented on DuckDuckGo/OnboardDefaultBrowserViewController.swift
> +class OnboardDefaultBrowserViewController: OnboardingContentViewController {
Good spotting on the `Browser` type – however we should keep the "Onboarding" part of the title. 🙂 

```suggestion
class OnboardingDefaultBrowserViewController: OnboardingContentViewController {
```

2022-08-03 20:07 UTC, byaruhaf commented
Thanks, @samsymons, 
I have accepted the correct for the one thing,😉
 I have a few other PR  I was working on for this repo so can be sending them through or wait for the freeze to end?

2022-08-04 04:43 UTC, samsymons commented
@byaruhaf I would recommend sitting on those for 2 weeks or so. 🙂 But, if you want to discuss those sooner than that, please do open a GitHub Issue – we usually prefer to discuss larger changes on an issue first before anyone spends too long on a PR.

2022-11-12 17:13 UTC, closed without merging