New privacy icon and blocked trackers animation
duckduckgo/iOS pull request #1288
Opened 2022-08-26 19:40 UTC by miasma13

Task/Issue URL: https://app.asana.com/0/0/1202099861623478/f
Tech Design URL:
CC:

**Description**:
This is intermediary PR for new privacy icon and blocked trackers animation.
Scope of the changes is:
- privacy icon (shield or shield with red dot) - that should trigger its animation upon loading, the privacy icon acts also as a button to open privacy dashboard
- blocked tracker animation - if there are blocked trackers their logos are crossed out in animation and rolled under the privacy icon

Note: This PR does not remove all old tracker assets as they are still used by the current dashboard.

**Scenarios to test this PR**:
Do a SERP search
- privacy icon is replaced by Dax logo
- privacy dashboard is inaccessible

Loading webpage with trackers being blocked (e.g. https://www.bbc.com )
- privacy icon animates force field
- blocked trackers are animated

Loading webpage when no trackers are blocked (e.g. https://www.wikipedia.org )
- privacy icon is shield
- no trackers are animated

Loading non-HTTPS webpage with trackers that are blocked (e.g. http://go.com )
- privacy icon shows red dot
- blocked trackers are animated

Loading webpage with disabled protection (e.g. disable privacy protection for loaded site )
- privacy icon shows red dot
- no trackers are animated

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

2022-08-30 21:24 UTC, bwaresiak commented
We should make sure this and https://github.com/duckduckgo/iOS/pull/1285 are compatible.

2022-09-02 13:06 UTC, Bunn requested changes
I've added some comments, nothing major.
The reason I'm requesting changes is that the most tests on `TrackersAnimatorTests` are failing.
Other than that looks very good, the new animation is amazing :)

2022-09-02 13:06 UTC, Bunn commented on Core/SiteRating.swift
> +        public static let majorNetworkPrevalence = 25.0
Why was this changed?

2022-09-02 13:06 UTC, Bunn commented on DuckDuckGo/PrivacyIconAndTrackersAnimator.swift
> +        UIView.animate(withDuration: 0.2) {
We have this 0.2 duration in 4 different places bellow (including this one), which makes me assume they should always share the same duration in case we want to change it later. Maybe add a const for this?

2022-09-02 13:06 UTC, Bunn commented on DuckDuckGo/PrivacyIconAndTrackersAnimator.swift
> +        currentTrackerAnimation?.play(toFrame: 45)  // stop frame for all 3 tracker animations
What is frame 45? 
Maybe a const with a name would make it easier to understand why we need to stop at this frame?

2022-09-02 13:06 UTC, Bunn commented on DuckDuckGo/PrivacyIconView.swift
> +        }
This can be removed

2022-09-07 06:09 UTC, miasma13 commented on DuckDuckGo/PrivacyIconView.swift
> +        }
👍

2022-09-07 06:10 UTC, miasma13 commented on Core/SiteRating.swift
> +        public static let majorNetworkPrevalence = 25.0
This based on the code coming from mac repo. Same update is done on Android.

2022-09-07 06:13 UTC, miasma13 commented on DuckDuckGo/PrivacyIconAndTrackersAnimator.swift
> +        currentTrackerAnimation?.play(toFrame: 45)  // stop frame for all 3 tracker animations
This is mid-point in tracker animation where all the circles are fully revealed but before they start to roll in.
It makes total sense to extract it as a const.

2022-09-07 06:13 UTC, miasma13 commented on DuckDuckGo/PrivacyIconAndTrackersAnimator.swift
> +        UIView.animate(withDuration: 0.2) {
👍

2022-09-08 12:33 UTC, Bunn commented on DuckDuckGo/PrivacyIconAndTrackersAnimator.swift
> +    static var allTrackersRevealedAnimationFrame = 45.0
Shouldn't it be `let` ?

2022-09-08 12:35 UTC, Bunn approved these changes
All tests are passing.

Just a small comment on a var/let question, but other than that, LGTM, nice job 🎉

2022-09-09 15:15 UTC, miasma13 commented on DuckDuckGo/PrivacyIconAndTrackersAnimator.swift
> +    static var allTrackersRevealedAnimationFrame = 45.0
👍

2022-09-09 15:16 UTC, merged