Cookie prompt management
duckduckgo/iOS pull request #1475
Opened 2023-01-27 22:41 UTC by miasma13

Task/Issue URL: https://app.asana.com/0/72649045549333/1201892492219034/f

**Description**:
- Support automatic cookie prompt management via autoconsent script
- Additionally hide cookie banners without reject button
- Present animated address bar notification whenever cookie pop-up is managed or hidden
- Promote the feature via Dax dialog on first encountered cookie pop-up by describing the feature and enabling opt-in
- Provide settings screen for the feature with toggle for its state and informative description
- Whenever cookie pop-up is managed or hidden show it in the privacy dashboard

**Additional notes:**
- list of websites for testing can be found in [Coverage testing](https://app.asana.com/0/0/1203843590207742/f)
- promoting Dax dialog is set to appear only for EU (checked via region of the phone set in iOS: Settings → General → Language & Region → Region)
- you can reset autoconsent settings via debug menu to restore default for the new app without the need of uninstalling it (also remember to clear cookies via fire button)
- promoting Dax dialog won't appear during onboarding

**Steps to test this PR**:
I. Dax dialog
1. Reinstall or reset autoconsent settings via debug menu
2. Ensure device's region is set to one in EU
3. Navigate to a page with cookie popup e.g. https://doodle.com/
4. Dax dialog for opt-in should appear
5. Test if selecting options adjusts settings

II. Cookies managed
1. When navigating for the first time to a page with cookie pop-up if feature is enabled a "Cookies managed" animated notification in the address bar should be presented following blocked trackers animation.
2. Privacy Dashboard should display an info about cookie pop-up

III. Pop-up Hidden
1. When navigating for the first time to a page with cookie pop-up that cannot be managed but hidden and if feature is enabled should present "Pop-up Hidden" animated notification in the address bar should be presented following blocked trackers animation.
2. Privacy Dashboard should display an info about cookie pop-up

IV. No Dax dialog outside EU
1. Reinstall or reset autoconsent settings via debug menu
2. Ensure device's region is NOT set to one in EU
3. Navigate to a page with cookie popup
4. Dax dialog should not be presented and the cookie pop-up shouldn't be dismissed (feature disabled by default)
5. Go to Settings -> Manage Cookie Pop-ups
6. Enable the feature with toggle
7. Cookie pop-ups should now be managed without Dax dialog being presented

V. No Dax dialog if feature was toggled manually in settings
1. Reinstall or reset autoconsent settings via debug menu
2. Ensure device's region is set to one in EU
3. Go to Settings -> Manage Cookie Pop-ups and enable the feature with toggle
4. Navigate to a page with cookie popup
5. Dax dialog should not be presented and the cookie pop-up should be dismissed

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

2023-01-30 11:02 UTC, muodov commented on DuckDuckGo/Autoconsent/AutoconsentUserScript.swift
> +  //          && !(AppDelegate.isRunningTests && url.path.hasSuffix("/autoconsent-test-page.html"))
I think it'd be good to port this integration test from macOS.
Are you planning to add some unit tests for the message handlers?

2023-02-05 17:06 UTC, jaceklyp requested changes

2023-02-05 17:06 UTC, jaceklyp commented on Core/LocaleExtension.swift
> +            .contains(where: { regionCode == $0 })
- how about .contains(regionCode)?
- also, regionCode has been deprecated and you should use language.region.identifier instead

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/Autoconsent/AutoconsentManagement.swift
> +    static let shared = AutoconsentManagement()
if we introduce singleton pattern perhaps we should make regular initializer private?

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/AutoconsentSettingsViewController.swift
> +class AutoconsentSettingsViewController: UITableViewController {
final

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/AutoconsentSettingsViewController.swift
> +    @IBOutlet weak var infoText: UILabel!
it is a good practice to make all outlets private

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/AutoconsentSettingsViewController.swift
> +    @IBAction func onAutoconsentValueChanged(_ sender: Any) {
private

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/BrokenSiteCategories.swift
> +        case cookieprompt
shouldn't it be cookiePrompt?

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/CookieConsentDaxDialogModel.swift
> +final class CookieConsentDaxDialogModel: CustomDaxDialogModel {
shouldn't we stick to one naming convention either CookiePrompt or CookieConsent?

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/CustomDaxDialog.swift
> +    @State var model: CustomDaxDialogModel
shouldn't it be viewModel?

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/CustomDaxDialog.swift
> +private enum Constants {
<3 this

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/CustomDaxDialog.swift
> +    var body: some View {
I'd love to see it constrained to SRP but in view scope -> it's difficult to follow if that computed var is so long - perhaps could we extract parts of it and rename it according to its behavior? please see: HomeMessageView's body

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/CustomDaxDialogModel.swift
> +protocol CustomDaxDialogModel {
should be ViewModel imho

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/OmniBarNotification.swift
> +    var body: some View {
same request as for previous body :)

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/OmniBarNotificationContainerView.swift
> +                                                ignoreSafeArea: true)
some indentation issue here

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/OmniBarNotificationContainerView.swift
> +        window?.rootViewController?.addChild(notificationViewController)
you should call controller.didMove(toParent: self) afterwards

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/OmniBarNotificationContainerView.swift
> +        currentNotificationController.removeFromParent()
you should call currentNotificationController.willMove(toParent: nil) before these two calls

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/OmniBarNotificationContainerView.swift
> +        self.currentNotificationController = nil
self is not needed here

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/OmniBarNotificationContainerView.swift
> +    private func makeNotificationModel(for type: OmniBarNotificationType) -> OmniBarNotificationModel {
ViewModel

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/OmniBarNotificationModel.swift
> +class OmniBarNotificationModel: ObservableObject {
final and ViewModel ;)

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/OmniBarNotificationModel.swift
> +    enum Duration {
private

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/OmniBarNotificationModel.swift
> +    let animationName: String
perhaps it can be private too

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/PrivacyDashboardViewController.swift
> +            case "cpm":
lets make it const somewhere

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/PrivacyIconAndTrackersAnimator.swift
> +        self.onAnimationCompletion = nil
selfs not needed here

2023-02-05 17:06 UTC, jaceklyp commented on DuckDuckGo/Triangle.swift
> +struct Triangle: Shape {
let's a one line doc here that it's a Isosceles triangle

2023-02-07 14:48 UTC, miasma13 commented on DuckDuckGo/OmniBarNotificationContainerView.swift
> +        self.currentNotificationController = nil
It is, since the `currentNotificationController` without `self` is guard unwrapped let.

2023-02-07 14:48 UTC, miasma13 commented on DuckDuckGo/OmniBarNotificationContainerView.swift
> +        self.currentNotificationController = nil
It is, since the currentNotificationController without self is guard unwrapped let.

2023-02-07 14:49 UTC, miasma13 commented on DuckDuckGo/OmniBarNotificationModel.swift
> +    let animationName: String
It cannot as it is externally read.

2023-02-08 08:27 UTC, miasma13 commented on DuckDuckGo/BrokenSiteCategories.swift
> +        case cookieprompt
Actually the string value is "cookieprompt" but maybe being explicit and putting it as `case cookiePrompt = "cookieprompt"` will make it verbose and avoid by mistake `fixing` the capitalisation in the future.

2023-02-08 08:46 UTC, miasma13 commented on DuckDuckGo/CookieConsentDaxDialogModel.swift
> +final class CookieConsentDaxDialogModel: CustomDaxDialogModel {
Throughout the code it is used as `CookieConsent` the only exception for using the `prompt` keyword was in the broken site category and it came from the string value required by the contract.

2023-02-08 11:12 UTC, miasma13 commented on DuckDuckGo/Autoconsent/AutoconsentUserScript.swift
> +  //          && !(AppDelegate.isRunningTests && url.path.hasSuffix("/autoconsent-test-page.html"))
I plan on looking at porting the integration tests later this week. For message handlers I was thinking about deferring it and having them in BSK when we move the shared user script code there.

2023-02-10 12:56 UTC, merged