Manage Duck Addresses
duckduckgo/iOS pull request #1828
Opened 2023-07-13 17:00 UTC by afterxleep

Task/Issue URL: https://app.asana.com/0/1142021229838617/1205057443326659/f

**Description**:
Allows you to manage your private Duck addresses

**Steps to test this PR**:
1. Enable Autofill
2. Create a login that includes a valid private Duck Address
3. Observe the management UI for the address is available
4. Enable and disable the duck Address
5. Observe state changes properly
6. Update the username of the login so the private address is no longer valid
7. Observe the management UI is not available anymore

**Other tests**
- Smoke test email and password generation

**Demo:**
![demo-2](https://github.com/duckduckgo/iOS/assets/1156669/1bd94524-e780-4cbf-9d13-082abc7c2070)

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2023-07-26 08:12 UTC, amddg44 requested changes
@afterxleep it looks like there is still an issue with state not being properly reset. I was running through your test steps and found (and can reproduce consistently):

- If I test 3b from a fresh app launch, everything is good
- If I test 3a, and then 3b in the same session my personal duck address saves automatically

I spent some time digging into this and it looks to me that `autogeneratedCredentials` in `SecureVaultManager` is not being reset correctly to false after 3a

My exact test steps were:
1. On `fill.dev` I generated a private address and entered a manual password
2. Credentials were saved automatically ✅ 
3. I deleted this login and went back and chose my personal duck address
4. Before entering a password or tapping submit, I checked Logins and found a partial login saved with my personal duck address

2023-07-27 13:17 UTC, afterxleep commented
@amddg44 Looking into this

2023-07-27 18:49 UTC, afterxleep commented
> * test 3a, and then 3b

@amddg44 I've made a couple minor updates to split the logic between autogenerated usernames and passwords, updated a test and [added a new one](https://github.com/duckduckgo/BrowserServicesKit/pull/396/commits/70466fd3beebb96681550879eb2f66a763be29f9#diff-c42229b6ba0ddb79302af9009d06c791f7d56ddf3c90bf43c86a7be3d81fd938R402) to cover for this particular scenario:

2023-07-28 16:47 UTC, afterxleep commented
@amddg44 

Thanks again for the review.  I've double checked and fixed **3c**, which as expected was also caused by the form submission autogenerated key not working on iOS as it does on Mac.   I also added a test for this, and manually tested 3d, 3e and 3f.

Changes to BSK [here](https://github.com/duckduckgo/BrowserServicesKit/pull/396/commits/b93cf42891f34f462a751a112c051446cc6c60bf)

2023-08-02 12:37 UTC, amddg44 requested changes
@afterxleep nice work! just a couple of nits (mostly removing some dead code) 🙂

2023-08-02 12:37 UTC, amddg44 commented on DuckDuckGo/TabViewController.swift
> -            if !autoSavedCredentialsId.isEmpty {
I think this var `autoSavedCredentialsId` can be safely deleted now that all that logic has moved to BSK

2023-08-02 12:37 UTC, amddg44 commented on DuckDuckGo/TabViewController.swift
> -                    deleteLoginFor(accountIdInt: accountIdInt)
Also this func `deleteLoginFor` can be deleted too since now since nothing is calling it

2023-08-02 12:37 UTC, amddg44 commented on DuckDuckGo/AutofillLoginDetailsView.swift
> +            .background(EmptyView().alert(isPresented: $viewModel.isShowingAddressUpdateConfirmAlert) {
Can this be simplified to something like this?
```
listWithBackground
          .alert(isPresented: $viewModel.isShowingAddressUpdateConfirmAlert) {
              let btnLabel = Text(viewModel.toggleConfirmationAlert.button)
              let btnAction = viewModel.togglePrivateEmailStatus
              let button = Alert.Button.default(btnLabel, action: btnAction)
              let cancelBtnLabel = Text(UserText.autofillCancel)
              let cancelBtnAction = { viewModel.refreshprivateEmailStatusBool() }
              let cancelButton = Alert.Button.cancel(cancelBtnLabel, action: cancelBtnAction)
              return Alert(
                  title: Text(viewModel.toggleConfirmationAlert.title),
                  message: Text(viewModel.toggleConfirmationAlert.message),
                  primaryButton: button,
                  secondaryButton: cancelButton)
          }
```

2023-08-03 08:36 UTC, amddg44 approved these changes

2023-08-03 13:34 UTC, merged