extract main view controller segues into extension
duckduckgo/iOS pull request #2045
Opened 2023-09-27 12:12 UTC by brindy

Task/Issue URL: https://app.asana.com/0/0/1205584556126566/f
Tech Design URL:
CC:

**Description**:

Extracts segues in the main view controller into an extension which is more programatic about opening what used to be storyboard references / segues.

**Steps to test this PR**:

1. 
2.

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16
* [ ] iOS 17

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2023-09-27 22:41 UTC, brindy commented on DuckDuckGoTests/PrivacyIconLogicTests.swift
> -    override func setUp() {
swiftlint on GitHub started complaining about unused overridden function

2023-09-27 22:45 UTC, brindy commented on DuckDuckGo/SaveLoginViewController.swift
> -    override func viewDidLayoutSubviews() {
SwiftLint override unused function

2023-09-27 22:47 UTC, brindy commented on DuckDuckGo/AutofillListItemTableViewCell.swift
> -    override func setSelected(_ selected: Bool, animated: Bool) {
SwiftLint override unused function

2023-09-27 22:47 UTC, brindy commented on DuckDuckGo/KeychainItemsDebugViewController.swift
> -    override func viewDidLoad() {
SwiftLint override unused function

2023-09-27 22:48 UTC, brindy commented on DuckDuckGo/SettingsViewController.swift
> -    override func tableView(_ tableView: UITableView, titleForFooterInSection section: Int) -> String? {
SwiftLint override unused function

2023-09-27 22:49 UTC, brindy commented on DuckDuckGoTests/TrackerAnimationLogicTests.swift
> -    override func setUp() {
SwiftLint override unused function

2023-09-27 22:49 UTC, brindy commented on IntegrationTests/AtbServerTests.swift
> -    override func tearDown() {
SwiftLint override unused function

2023-09-29 21:30 UTC, miasma13 requested changes
There are couple of leftover performSegues that trigger assertion in MainViewController:
- AppDelegate.swift L:705
- AppTPHomeViewModel.swift L:90

2023-09-29 21:30 UTC, miasma13 commented on DuckDuckGo/MainViewController+Segues.swift
> +        }
You missed `bookmarks.delegate = self` here. Without the delegate tapping a bookmark has no effect.

2023-09-29 21:30 UTC, miasma13 commented on DuckDuckGo/MainViewController+Segues.swift
> +    private func hideAllHilightsIfNeeded() {
Typo? hilights -> highlights

2023-10-02 12:09 UTC, miasma13 approved these changes
Works as expected 👍

2023-10-02 12:11 UTC, merged