Sabrina/sync setup update
duckduckgo/iOS pull request #2198
Opened 2023-11-27 16:24 UTC by SabrinaTardio

Task/Issue URL: https://app.asana.com/0/0/1205948195318715/f

**Description**: Update the sync UI flow according to https://www.figma.com/file/5wIXwQLKJ0dZVsP5XWcgbT/%F0%9F%8E%AF-Sync-9?type=design&node-id=8748-306047&mode=design&t=5IygRcQcvvNAJ7xg-0

**Steps to test this PR**:
1. Go to Sync Settings check UI and copy looks as expected

Sync This Device Flow
1. Go to Sync Settings check UI and copy looks as expected
3. Click on Sync and Back Up this device check “Sync and Back Up this device” sheet appears and design and copy are as expected
4. Click on “Turn on Sync & Backup”
5. Check preparing to sync sheet appears briefly before Save Recovery Code appears (check copy and UI)
6. Check save as PDF and copy code work as expected
7. Press Next and check Your Data is Synced! sheet appears.
8. Press done and check sync enabled view appears (check looks as expected)
9. Delete account

Recover Synced Data flow
1. Click on Recover Synced Data and check Recover Synced Data sheets appear and looks as expected
2. Click on Get Started and check the recover synced data camera mode appears 
3. Try to scan a recovery QR code or other device code and check the flow appears as in the previous case
4. Try the same with Enter text Code manually

Sync with Another device flow
1.  Click on Sync with Another Device
2. Check the Scan QR code camera view appears
3.  Try to point to a QR code of both a connected device and later an unconnected device and check the flow
4. Same by manually inserting the code
5. Same when scanning the QR code presented from another device
6. Same when copying the text in another device.

Sync enabled View
Check sync with another device work as expected: the same ScanQR code view should appear and you should be able to connect a new device.

<!—
Before submitting a PR, please ensure you have tested the combinations you expect the reviewer to test, then delete configurations you *know* do not need explicit testing.

Using a simulator where a physical device is unavailable is acceptable.
—>

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `’`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

—
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2023-11-29 23:05 UTC, brindy requested changes
A few comments for you. I still need to do the actual testing.

2023-11-29 23:05 UTC, brindy commented on DuckDuckGo/SyncSettingsViewController+PDFRendering.swift
> +                                                                       overrideInterfaceStyle: .dark) { _, _, _, _ in }
The completion handler is optional so might as well remove it.

2023-11-29 23:05 UTC, brindy commented on DuckDuckGo/SyncSettingsViewController.swift
> +        }
This would be better as a guard.  The reason being this entire function depends on these two conditions being true - and bonus it'll reduce some indenting.

```suggestion
        guard let presentedViewController = navigationController?.presentedViewController,
              !(presentedViewController is UIHostingController<SyncSettingsView>) else { return }
        presentedViewController.dismiss(animated: true, completion: nil)
        endConnectMode()
```

2023-11-29 23:05 UTC, brindy commented on LocalPackages/SyncUI/Sources/SyncUI/Views/PasteCodeView.swift
> +        )
The problem with this approach is it's going to be almost impossible to localise. In other languages this is all going to be out of order.  Since this is iOS it'd be better to have a single piece of text and use markup. We'll be dropping iOS 14 soonish so it should be fine if the markup doesn't render properly on all devices.

Check out `UserText.aboutText` in the main app.

Sorry if this is not new, I must have missed it last time.

2023-11-29 23:05 UTC, brindy commented on LocalPackages/SyncUI/Sources/SyncUI/Views/PreparingToSync.swift
> +
The pattern / convention is to call these Whatever*View*, e.g. `PreparingToSyncView`

2023-11-29 23:05 UTC, brindy commented on LocalPackages/SyncUI/Sources/SyncUI/Views/RecoverSyncedData.swift
> +public struct RecoverSyncedData: View {
Struct name

2023-11-29 23:05 UTC, brindy commented on LocalPackages/SyncUI/Sources/SyncUI/Views/ScanOrEnterCodeToRecoverSyncedData.swift
> +public struct ScanOrEnterCodeToRecoverSyncedData: View {
Struct name

2023-11-30 10:01 UTC, brindy commented
Still testing, but here's a few things:

1/ Alignment of text "Your data is end to end encrypted..." is wrong
<img width="402" alt="Screenshot 2023-11-30 at 09 27 27" src="https://github.com/duckduckgo/iOS/assets/81197/b6b9e3ac-1d33-4a8c-8237-3f6a73be6456">

2/ Tap "Sync with another device" button:
	* Tap manually enter the code 
	* Tap back - QR Code is wrong.  Scanning this with another devices causes an assertion.
![Simulator Screenshot - iPhone 15 Pro - 2023-11-30 at 09 43 03](https://github.com/duckduckgo/iOS/assets/81197/03cdb93c-2326-4613-acd1-622d06201d28)

3/ Tap "Sync with another device" button:
	* Tap manually enter the code 
	* Paste a invalid code 
	* Bug: Shows "validating code" and doesn't move on (used to show an error)
![Simulator Screenshot - iPhone 15 Pro - 2023-11-30 at 10 00 04](https://github.com/duckduckgo/iOS/assets/81197/7818b3ab-09de-48dc-af6e-6f95f18bdad4)

4/ Tap "Sync with another device" button:
	* Tap manually enter the code 
	* Paste a valid code
	* Bug: Shows "setting up sync and backup screen" "connecting..." and doesn't move on.  Sliding it away shows that sync connected.
![Simulator Screenshot - iPhone 15 Pro - 2023-11-30 at 09 40 31](https://github.com/duckduckgo/iOS/assets/81197/d224ef73-f929-4b94-950e-a17e279d6ef7)

2023-11-30 10:27 UTC, brindy commented on DuckDuckGo/SettingsViewController.swift
> +        return true
Did you mean to commit this?

2023-11-30 10:52 UTC, SabrinaTardio commented on DuckDuckGo/SettingsViewController.swift
> +        return true
nope I just pushed it now by mistake

2023-12-01 11:25 UTC, brindy commented on LocalPackages/SyncUI/Sources/SyncUI/Views/SyncWithServer.swift
> +public struct SyncWithServer: View {
Struct name 😬

2023-12-01 11:49 UTC, brindy approved these changes
1 comment but otherwise LGTM

2023-12-01 12:07 UTC, merged