clean up clear data code
duckduckgo/iOS pull request #2449
Opened 2024-02-07 23:24 UTC by brindy

Task/Issue URL: https://app.asana.com/0/414235014887631/1206545081824897/f
Tech Design URL:
CC:

**Description**:
Cleans up the clear data code and makes it use the async/await API.

It's important to test this on iOS 17 and an earlier version of iOS as there are two paths depending on OS version.

**Steps to test this PR**:

1. Go to setcookie.net and set a cookie (save it as a favourite too for convenience).  Refresh the page to confirm it has been set.
2. Use the fire button
3. Go back to setcookie.net - cookie should gone
4. Set another cookie and fire proof the site
5. Use the fire button
6. Cookie should be retained
7. Use the fire button a couple of times in a row
8. Cookie should still be present
9. Go to settings and remove the site from the list of fireproofed sites
10. Refresh the site and the cookie should have been removed
11. Do a search and on the SERP change a setting (e.g. safe search to off)
12. Use the fire button
13. Go back to the SERP - the setting should be retained
14. Login to some websites and fireproof - check that you stay logged in.
15. Remove fireproofing - check that you are logged out

2024-02-14 19:24 UTC, bwaresiak requested changes
I've tested this a lot Today, and found two issues:

1. When using Auto Clear data, fireproofing doesn't seem to work when I kill and restart the app.
2. When data clear animation is set to "None" URL is not cleared from URL bar.

Other than this good job @brindy:

- Tested both iOS 15 and 17.
- Upgrading app works fine.
- With regular animation I could not reproduce the problem with URL bar glitch/data.
- Tested various scenarios, opening, navigating, clearing, reopening, restarting... all of these worked as expected.

2024-02-19 07:48 UTC, bwaresiak requested changes
Tested it this morning found two problems:
1. Auto clear doesn't seem to remove cookies on restart. :)
2. Blank Snapshot view has empty space instead of search bar.
![IMG_0704](https://github.com/duckduckgo/iOS/assets/2865434/b79f2380-b8df-40fc-b962-3efc6f500669)

2024-02-19 07:48 UTC, bwaresiak commented on DuckDuckGo/AppDelegate.swift
> +//        }
Remove? :)

2024-02-19 07:48 UTC, bwaresiak commented on DuckDuckGo/MainViewController.swift
> +    var dataStoreReadiness: DataStoreWarmup? = DataStoreWarmup()
readiness or a warmup? ;)

2024-02-19 11:33 UTC, brindy commented
@bwaresiak haven't addressed the missing bar on the empty view because I think that is not related to this change, right?

2024-02-19 13:54 UTC, bwaresiak approved these changes
Great job!

2024-02-19 13:56 UTC, merged