Use toast experiment to identify behavioral signal of breakage
duckduckgo/iOS pull request #2790
Opened 2024-04-25 11:13 UTC by jaceklyp

Task/Issue URL: https://app.asana.com/0/72649045549333/1206282120976009/f
Tech Design URL:  https://app.asana.com/0/481882893211075/1207131142774546/f (experiment related)

**Description**:
Identify a user behavioral action that is indicative of breakage through the use of a toast that 'activates' after certain user actions and asks the user to confirm if they are experiencing breakage

**Steps to test this PR**:
https://app.asana.com/0/0/1207169356692220/f

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

2024-04-25 15:32 UTC, brindy requested changes
a few comments just now, but on major thing - I am not sure your localised strings are right, you seem to have removed the ones related to the new crash functionality?  Or have I misunderstood?

I will do functional testing in the morning.

2024-04-25 15:32 UTC, brindy commented on DuckDuckGo/MainViewController.swift
> +    private var host: UIHostingController<BrokenSitePromptView>?
This is specific to the broken site thing, so should be named appropriate.y

2024-04-25 15:32 UTC, brindy commented on DuckDuckGo/UserBehaviorMonitor.swift
> +            if didRefreshCounter == 3 {
`> 2` is a safer option incase that counter gets incremented unexpectedly, to avoid this getting in a weird state that never gets called

2024-04-25 15:32 UTC, brindy commented on DuckDuckGo/SettingsHostingController.swift
> +        if PixelExperiment.cohort == .newSettings {
if you're gonna make this kind of change, a ternary is more concise imo

    let settingsView = PixelExperiment.cohort == .newSettings ? 
         AnyView(SettingsRootView(viewModel: viewModel)) : 
         AnyView(SettingsView(viewModel: viewModel))

2024-04-26 14:02 UTC, brindy requested changes
just spotted something else (and the cohort/install thing as we discussed on MM)

2024-04-26 14:02 UTC, brindy commented on DuckDuckGo/BrokenSitePromptView.swift
> +                + Text("\n")
Do you really need a new line character here? it's in a VStack so will be below anyway

2024-04-26 14:02 UTC, brindy commented on DuckDuckGo/UserBehaviorMonitor.swift
> +                PixelExperiment.install() // Do we have better place to install it?
This should not be called here - there is a line commented out in the AppDelegate that is responsible for this which will be commented in when @tomasstrba 's experiment goes live.  Cohorts are allocated at the point you access the `.cohort` variable.

2024-04-26 14:26 UTC, jaceklyp commented on DuckDuckGo/BrokenSitePromptView.swift
> +                + Text("\n")
Good question! This is how I initially did it, but then spacing (8) on VStack applies to these two Texts which is not what I wanted. I'll be happy to know if there's a better way!

2024-05-12 23:50 UTC, brindy commented on DuckDuckGo/MainViewController.swift
> +        guard /*userDidInteractWithBrokenSitePrompt,*/
What's this comment about?

2024-05-12 23:56 UTC, brindy commented on DuckDuckGo/UserBehaviorMonitor.swift
> +//                if PixelExperimentForBrokenSites.cohort == eventToFire.matchingPixelExperimentVariant {
Deliberate comment?

2024-05-14 16:07 UTC, brindy approved these changes
LGTM - appears to work as intended.  We discussed the UI/animation approach during the project so I'm happy with that.  Just a reminder to remove or uncomment any commented out code, specifically:

* UserBehaviourMonitor:108 + 112
* and the guard `/*!userDidInteractWithBrokenSitePrompt,*/`

Good job!

2024-05-14 23:26 UTC, merged