Add feature flag for improved New Tab Page
duckduckgo/iOS pull request #2980
Opened 2024-06-21 11:01 UTC by dus7

- **Add Home Tab improvements internal flag**
- **Define a protocol for HomeViewController**
- **Show proper home tab view based on the feature flag**
- **Add Home tab section to Debug menu**

Task/Issue URL:
Tech Design URL:
CC:

**Description**:

**Steps to test this PR**:
1.
2.

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2024-06-24 15:16 UTC, brindy commented on DuckDuckGo/HomeTabViewController.swift
> +//  ImprovedHomeViewController.swift
SwiftLint - presume you renamed the file or something during dev

2024-06-24 15:17 UTC, brindy commented on DuckDuckGo/HomeTabViewController.swift
> +final class HomeTabViewController: UIHostingController<HomeTabView>, HomeViewControllerProtocol {
Wonder if we should just go all in on calling it 'new tab page' ?  e.g.

`NewTabPageViewController` 

?

2024-06-24 15:23 UTC, brindy requested changes
Hey, looks good and works. Needs some renaming, SwiftLint, and resolve conflicts. Give me a ping for a follow up review.

2024-06-24 15:23 UTC, brindy commented on DuckDuckGo/HomeViewControllerProtocol.swift
> +protocol HomeViewControllerProtocol: UIViewController {
Let's avoid calling protocols "Protocol" - I know we have some in the code base already, but imo they need refactored.  From the API Design Guidelines:

* Protocols that describe what something is should read as nouns (e.g. Collection).

* Protocols that describe a capability should be named using the suffixes able, ible, or ing (e.g. Equatable, ProgressReporting).

I think the protocol here is simply `NewTabPage` but open to suggestion.

2024-06-24 15:23 UTC, brindy commented on DuckDuckGo/RootDebugViewController.swift
> +        case homeTabImprovements = 674
I'm not overly keen on this.  Would be better to capture the cell as an outlet and check that. However, looks like we're invested in this approach.  We should probably refactor this debug view controller at some point. :) 

(No action required)

2024-06-24 16:55 UTC, dus7 commented on DuckDuckGo/HomeTabViewController.swift
> +final class HomeTabViewController: UIHostingController<HomeTabView>, HomeViewControllerProtocol {
Yeah, probably. I was hesitating and left one similar to what's now, but maybe it's better to keep consistency with internal names.

2024-06-24 18:01 UTC, dus7 commented on DuckDuckGo/MainViewController.swift
> +    var homeController: NewTabPage? {
I left `homeController` here deliberately to avoid extensive renaming. It'll be done after the old code gets cleaned up.

2024-06-25 03:59 UTC, brindy approved these changes
FYI I pushed a swiftlint fix

LGTM!

2024-06-25 10:23 UTC, merged