Onboarding Contextual Tutorial Rendering
duckduckgo/iOS pull request #3063
Opened 2024-07-10 10:03 UTC by alessandroboron

Task/Issue URL: https://app.asana.com/0/72649045549333/1207701578629995/f
CC: @SabrinaTardio 

**Description**:

This PR changes the rendering of the onboarding contextual messages based on the cohorts.

For cohort `ma` show the Old onboarding overlays
For cohort `mb` show the new Dax Contextual Dialogs.

**Video**

https://github.com/duckduckgo/iOS/assets/1089358/3bfb3955-cb8d-4454-b541-eb5ba0ad29d9

**Steps to test this PR**:

**SCENARIO 1 - Old Onboarding**
Prerequisites: Delete DuckDuckGo App from Simulator.

1. DuckDuckGo Scheme -> Run -> Arguments -> Environment Variables -> VARIANT -> `ma`
2. Add temporary `newInstallCompletion(self)` at line 141 in `DefaultVariantManager`
3. Launch the App.
4. Complete the Onboarding Intro.
5. The New Tab Page should show the old Dax Dialog.
6. Follow the instructions and input a website (e.g. “facebook.com”) into the address bar.
**Expected Result:** An overlay informing the user about the trackers blocked should appear on top of the screen.
8. Dismiss the overlay.
9. Tap the fire Button.
**Expected Result:** The action sheet to clear the data should appear on the screen along with an overlay informing the user about the fire button.

**SCENARIO 2 - New Onboarding**
Prerequisites: Delete DuckDuckGo App from Simulator.

1. DuckDuckGo Scheme -> Run -> Arguments -> Environment Variables -> VARIANT -> `mb`
2. Add temporary `newInstallCompletion(self)` at line 141 in `DefaultVariantManager`
3. Launch the App
4. Complete the Onboarding Intro.
5. The New Tab Page should show the old Dax Dialog.
6. Follow the instructions and input a website (e.g. “facebook.com”) into the address bar.
**Expected Result:** The Web page should shift down and the Dax Contextual Dialog should appear on the screen.
7. Tap the action button of the Dax Contextual Dialog. 
**Expected Result:** The Dax Contextual Dialog should disappear and the web page shift up.
8. Tap the fire Button.
**Expected Result:** The action sheet to clear the data should appear on screen but it should not show any overlay.

**Definition of Done (Internal Only)**:

* [ ] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `’`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 15
* [ ] iOS 16
* [ ] iOS 17

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

—
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2024-07-10 10:13 UTC, alessandroboron commented on DuckDuckGo.xcodeproj/project.pbxproj
> -		9F2510142BF5809E0096DB16 /* SubscriptionFlowViewModelTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = 9F2510132BF5809E0096DB16 /* SubscriptionFlowViewModelTests.swift */; };
These were Recovered References due to a merge conflict issue. I checked the code and `SubscriptionFlowViewModelTests.swift` and `SubscriptionContainerViewModelTests.swift` are still part of the project.

2024-07-10 10:16 UTC, alessandroboron commented on DuckDuckGo/Base.lproj/Tab.storyboard
>                          <subviews>
To simplify the review:
- I’ve added a vertical stack view and pinned its edges to the superview.
-I moved the webViewContainer within the stackview.

2024-07-10 10:27 UTC, alessandroboron commented on DuckDuckGo/OnboardingExperiment/ContextualOnboarding/ContextualOnboardingPresenter.swift
> +        controller.view.alpha = 0
AFAIR I hadn't set the alpha to animate the appearance/disappearance of a view in a stack view. However, without it, the view simply appears without any animation. The disappearance works fine without the alpha 😕

2024-07-10 10:27 UTC, alessandroboron commented on DuckDuckGo/OnboardingExperiment/ContextualOnboarding/ContextualOnboardingPresenter.swift
> +protocol TabViewControllerType: UIViewController {
For testing the presenter

2024-07-10 13:20 UTC, brindy requested changes
This works as advertised! :) 

However, in the onboarding flow on iPad mini in landscape Dax is cut off on the welcome view and the bottom of the dax dialog is lost on the browser comparison. 

I've asked on the ship review for Figma updates showing different screen sizes and orientations so that we know what scale to expect, but if you don't get any feedback by the time you're back on it, please just do your best to get it looking reasonable :)

2024-07-17 00:39 UTC, alessandroboron commented
> This works as advertised! :)
> 
> However, in the onboarding flow on iPad mini in landscape Dax is cut off on the welcome view and the bottom of the dax dialog is lost on the browser comparison.
> 
> I've asked on the ship review for Figma updates showing different screen sizes and orientations so that we know what scale to expect, but if you don't get any feedback by the time you're back on it, please just do your best to get it looking reasonable :)

This is now rebased on top of main contextual feature branch and contains the fixes for iPad mini in landscape

2024-07-18 11:43 UTC, brindy approved these changes
LGTM

2024-07-18 21:56 UTC, merged