Properly handle responses that should trigger download action
duckduckgo/iOS pull request #3407
Opened 2024-09-27 13:39 UTC by miasma13

Task/Issue URL: https://app.asana.com/0/414709148257752/1208359719493827/f

**Description**:
...

**Steps to test this PR**:
See parent task for set of download scenarios to test. _Please compare behavior with version from before changes._

**Definition of Done (Internal Only)**:

* [ ] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2024-09-27 13:39 UTC, miasma13 commented on DuckDuckGo.xcodeproj/project.pbxproj
> -		B6CB93E5286445AB0090FEB4 /* Base64DownloadSession.swift in Sources */ = {isa = PBXBuildFile; fileRef = B6CB93E4286445AB0090FEB4 /* Base64DownloadSession.swift */; };
No longer used anywhere.

2024-09-27 13:40 UTC, miasma13 commented on Core/PixelEvent.swift
> -        case .unhandledDownload: return "m_d_unhandled_download"
Looking at the code path and confirming in Kibana this pixel is/was not being fired.

2024-09-27 13:43 UTC, miasma13 commented on DuckDuckGo.xcodeproj/project.pbxproj
> +				1E5918462CA422A7008ED2B3 /* Navigation */,
Required for `WKNavigationAction`, `HTTPURLResponse` and other navigation related extensions.

2024-09-27 13:44 UTC, miasma13 commented on DuckDuckGo/TabViewController.swift
> -                } else {
Logical order of if-else has been reversed here.

2024-09-27 13:50 UTC, miasma13 commented on DuckDuckGo/TabViewController.swift
> +    private var recentNavigationActionShouldPerformDownloadURL: URL?
This is used to hold and pass information from `WKNavigationAction`'s  `shouldPerformDownload` read in: 
- `func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void)`

to be used for decision logic later in:
- `func webView(_ webView: WKWebView, decidePolicyFor navigationResponse: WKNavigationResponse, decisionHandler: @escaping (WKNavigationResponsePolicy) -> Void)`

and
- `func webView(_ webView: WKWebView, navigationResponse: WKNavigationResponse, didBecome download: WKDownload)`

2024-09-27 13:53 UTC, miasma13 commented on DuckDuckGo/TabViewController.swift
> +           !navigationAction.shouldDownload,
These are required changes for GPC protected sites not to break IFrame triggered downloads, as canceling and re-triggering request breaks the download attribute. This matches the logic on macOS where for page sub-requests we do not trigger the full distributed navigation chain execution. Aligned and accepted by the privacy team.

2024-10-15 12:48 UTC, brindy commented on DuckDuckGo/TabViewController.swift
> +        let shouldTriggerDownloadAction = hasContentDispositionAttachment || hasNavigationActionRequestedDownload || !canLoadOrPreviewTheFile
None of this is used more than once and the `shouldTriggerDownloadAction` is used *after* a bunch of other evaluations.  How about making that a private function that is called instead at the time it's relevant?

2024-10-15 12:49 UTC, brindy commented on DuckDuckGo/TabViewController.swift
> +                  let downloadMetadata = AppDependencyProvider.shared.downloadManager.downloadMetaData(for: navigationResponse.response) {
Now would be a really nice time to refactor out this singleton 😇

2024-10-15 13:14 UTC, brindy requested changes
~~Something isn't quite right.  I happened to be on this page and it triggers a download~~

~~https://duckduckgo.com/email/~~

~~But also doing a search triggers the download.~~

Edit: my fault, I changed some code when testing.

2024-10-16 12:13 UTC, brindy approved these changes
LGTM, thanks!

2024-10-16 12:19 UTC, merged