Malicious site protection navigation detection
duckduckgo/iOS pull request #3707
Opened 2024-12-10 12:37 UTC by alessandroboron

Task/Issue URL: https://app.asana.com/0/1206329551987282/1207151848931030
Tech Design URL: https://app.asana.com/0/1206329551987282/1207273224076495/f

**Description**:

This PR adds the navigation logic for detecting a malicious site and navigating to a special error page if the site is malicious.

The original idea in the tech design was to intercept the Request in `decidePolicyForNavigationAction` and check whether a site is malicious cancelling the request accordingly.

We noticed that the above approach increases the page load time of websites due to the logic check.

I opted for an approach where in `decidePolicyForNavigationAction` we start the detection task in parallel without waiting and in `decidePolicyForNavigationResponse` we evaluate the task’s result.

Another approach I thought of was to perform the logic in the background in `didStartProvisionalNavigation`. The problem with this approach is that is called only for navigation that starts from the main frame so it would not be possible to intercept malicious iFrame URLs.

**NOTE** 
BSK Threat detection is currently mocked. Its integration and tests will follow in an upcoming PR.

**Steps to test this PR**:
1.
2.

**Definition of Done (Internal Only)**:

* [ ] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 15
* [ ] iOS 16
* [ ] iOS 17

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2024-12-10 12:58 UTC, alessandroboron commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageInterfaces/SpecialErrorPageActionHandler.swift
> +    func visitSite(url: URL, errorData: SpecialErrorData)
I’m a bit on the fence with this. 
The idea was to have a generic protocol that all the sub-special error handlers should conform to. 
For `MaliciousSiteProtectionNavigationHandler` I need to pass the URL and SpecialErrorData but I don’t need them for the SSL handler. So I feel I’m violating the Interface Segregation principle. what do you think?

2024-12-10 12:59 UTC, alessandroboron commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageNavigationHandler+MaliciousSite.swift
> +                // Extract the URL of the source frame (the iframe) that initiated the navigation action
I will look more into iFrame logic when I integrate with BSK

2024-12-10 13:00 UTC, alessandroboron commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageNavigationHandler+MaliciousSite.swift
> +        // TODO: check storing redirects
Will address this TODO in upcoming PR

2024-12-10 13:01 UTC, alessandroboron commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageNavigationHandler+SSL.swift
> +    func visitSite(url: URL, errorData: SpecialErrorData) {
See comment https://github.com/duckduckgo/iOS/pull/3707/files#r1878050527

2024-12-20 18:05 UTC, jaceklyp requested changes

2024-12-20 18:05 UTC, jaceklyp commented on DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift
> +        case "http://privacy-test-pages.site/security/badware/malware.html":
should it be http vs https?
also, we should be keeping all urls inside AppURLs

2024-12-20 18:05 UTC, jaceklyp commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageInterfaces/SpecialErrorPageActionHandler.swift
> +    func visitSite(url: URL, errorData: SpecialErrorData)
could you perhaps create two funcs visitSite, one without params and one with params? Different handlers would be implementing only one function leaving other implementation empty? It's not ideal but the simplest

2024-12-20 18:05 UTC, jaceklyp commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageInterfaces/WebViewNavigationHandling.swift
> +    func handleDecidePolicyFor(navigationAction: WKNavigationAction, webView: WKWebView)
I think it should be
func handleDecidePolicy(for navigationAction: WKNavigationAction, webView: WKWebView)

2024-12-20 18:05 UTC, jaceklyp commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageInterfaces/WebViewNavigationHandling.swift
> +    func handleDecidePolicyfor(navigationResponse: WKNavigationResponse, webView: WKWebView) async -> Bool
typo, "for" is lowercased, but I'd refer to my previous comment ^

2024-12-20 18:05 UTC, jaceklyp commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageNavigationHandler+MaliciousSite.swift
> +    func createMaliciousSiteDetectionTask(for navigationAction: WKNavigationAction, webView: WKWebView)
I'd go with makeMalicious*

2024-12-20 18:05 UTC, jaceklyp commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageNavigationHandler+MaliciousSite.swift
> +        let threatDetectionTask: Task<MaliciousSiteProtectionNavigationResult, Never> = Task.detached { [weak self] in
why is the Task detached?

2024-12-20 18:05 UTC, jaceklyp commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageNavigationHandler+MaliciousSite.swift
> +        }
can we put it under one guard, like so
guard let url = navigationAction.request.url, url != URL(string: "about:blank") else { return }

2024-12-20 18:05 UTC, jaceklyp commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageInterfaces/SpecialErrorPageActionHandler.swift
> +    func visitSite(url: URL, errorData: SpecialErrorData)
However, if we encounter more cases like this where we’re stretching these protocols, we might need to reconsider whether it’s appropriate to treat all special errors the same way. For example, SSL and malicious site errors already exhibit different behaviors. I’ll leave it up to you, but perhaps we should treat them differently (not under same logic) from the start. We can discuss further in 2025 :)

2024-12-20 18:05 UTC, jaceklyp commented on DuckDuckGo/TabViewController.swift
> +        Task { @MainActor in
Whoa :), this is triggering an alert for me. Making a task on this code could have bigger consequences – we’re essentially returning immediately and skipping the run loop, without a guarantee that other tasks spawned elsewhere won’t interfere with this. Are we sure this is the approach we want to take?

2025-01-07 01:06 UTC, alessandroboron commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageInterfaces/SpecialErrorPageActionHandler.swift
> +    func visitSite(url: URL, errorData: SpecialErrorData)
I think I will use two functions one without params and one with params as you suggested. I will make them optionals by having an empty implementation in a protocol extension so different handlers will implement only the one needed.

2025-01-07 01:07 UTC, alessandroboron commented on DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift
> +        case "http://privacy-test-pages.site/security/badware/malware.html":
This is just for testing purposes. We won’t have any hardcoded website URLs in the upcoming BSK integration PR :)

2025-01-07 06:17 UTC, alessandroboron commented on DuckDuckGo/SpecialErrorPage/SpecialErrorPageNavigationHandler+MaliciousSite.swift
> +        let threatDetectionTask: Task<MaliciousSiteProtectionNavigationResult, Never> = Task.detached { [weak self] in
My bad, there’s no reason to have this task detached, I will convert it to a normal task.

2025-01-07 06:37 UTC, alessandroboron commented on DuckDuckGo/TabViewController.swift
> +        Task { @MainActor in
The problem is that here we should be able to retrieve the task and wait on it if the operation hasn’t completed yet. Eg. In some scenarios we need to check with the backend if a website is malicious and this could take few seconds.

What if we convert the `WKNavigationDelegate` [decidePolicyFor navigationResponse](https://developer.apple.com/documentation/webkit/wknavigationdelegate/webview(_:decidepolicyfor:decisionhandler:)-19mn2) to its async counterpart? In this way we can perform the asynchronous operation in a controlled manner.

Happy to jump on a zoom call to discuss the possible approaches.

2025-01-10 04:47 UTC, alessandroboron commented on DuckDuckGo/TabViewController.swift
> +        Task { @MainActor in
I converted [decidePolicyFor navigationResponse](https://developer.apple.com/documentation/webkit/wknavigationdelegate/webview(_:decidepolicyfor:decisionhandler:)-19mn2) to its async counterpart as agreed.

I carefully checked that the values returned in the function are the same ones previously passed to the decisionHandler closure. I also smoked test the [download test sites](https://app.asana.com/0/414709148257752/1208359719493827/f) and everything looks good to me.

2025-01-13 09:32 UTC, jaceklyp approved these changes

2025-01-14 02:17 UTC, merged