Malicious site protection address bar and privacy dashboard changes
duckduckgo/iOS pull request #3718
Opened 2024-12-11 17:02 UTC by alessandroboron

Task/Issue URL: https://app.asana.com/0/1206329551987282/1208959082985728/f

**Description**:

This PR addresses the following:
1. Updates the Privacy Icon to use the globe asset when visiting special error pages (SSL error included).
2. Updates the Privacy icon to use the alert asset when the user accepts the risk of visiting a malicious page. 
3. Show an updated privacy dashboard for phishing and malware special error pages.
 
**Steps to test this PR**:

**Scenario 1 - Special Error Pages show globe icon in the address bar**
Ensure that the below URLs show the globe icon in the Address Bar as per [Figma Design](https://www.figma.com/design/uP27mEGEaHCI7ZYXAs1815/Safe-Browsing-Warnings?node-id=1117-11982&t=q2JK6BSTmudDahx9-1)
1. http://privacy-test-pages.site/security/badware/phishing.html
2. http://privacy-test-pages.site/security/badware/malware.html
3. https://expired.badssl.com/ (or any other SSL error URL)

**Scenario 2 - Malicious Sites show alert icon in the address bar**
1. Navigate to the below websites
  a. http://privacy-test-pages.site/security/badware/phishing.html
  b. http://privacy-test-pages.site/security/badware/malware.html
2. When the special error page is shown, tap “Advanced” button and then tap the “Accept Risk adn Visit Site” button.
3. Ensure that the address bar show an alert as per [Figma Design](https://www.figma.com/design/uP27mEGEaHCI7ZYXAs1815/Safe-Browsing-Warnings?node-id=1139-35428&t=q2JK6BSTmudDahx9-1)

**Scenario 3 - Malicious Sites show updated privacy dashboard**
1. Navigate to the below websites
  a. http://privacy-test-pages.site/security/badware/phishing.html
  b. http://privacy-test-pages.site/security/badware/malware.html
2. When the special error page is shown, tap “Advanced” button and then tap the “Accept Risk adn Visit Site” button.
3. Tap the alert icon to open the Privacy Dashboard.
4. Ensure that the Privacy dashboard inform the user of deceptive website

**Scenario 4 - Accepting visiting SSL Insecure website (Bonus Point)**
1. Navigate to one of the malicious website.
2. Accept navigating to the website.
3. Navigate to https://expired.badssl.com/.
4. Ensure the globe icon is shown instead of the alert icon.
5. Accept the risk of visiting the site.
6. Ensure the shield icon is shown instead of the alert icon.

**Definition of Done (Internal Only)**:

* [ ] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPhone 14 Pro
* [ ] iPad

**OS Testing**:

* [ ] iOS 15
* [ ] iOS 16
* [ ] iOS 17

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2024-12-20 17:19 UTC, jaceklyp requested changes

2024-12-20 17:19 UTC, jaceklyp commented on DuckDuckGo/OmniBar.swift
> +        }
how does it look like for ssl error page now? I remember decision was not to show any icon, are we good there?

2024-12-20 17:19 UTC, jaceklyp commented on DuckDuckGo/PrivacyIconView.swift
> +    fileprivate var staticImage: UIImage? {
why static?

2024-12-20 17:19 UTC, jaceklyp commented on DuckDuckGo/TabViewController.swift
> +                                      malicousSiteThreatKind: specialErrorPageNavigationHandler.currentThreatKind,
typo; malicous

2025-01-07 06:38 UTC, alessandroboron commented on DuckDuckGo/OmniBar.swift
> +        }
Before this change we didn’t show any icon. We agreed to show the same icon for the special error pages, SSL included.

2025-01-07 06:41 UTC, alessandroboron commented on DuckDuckGo/PrivacyIconView.swift
> +    fileprivate var staticImage: UIImage? {
Probably not a great name if it raises questions. As `shield` and `shieldWithDot` are animated I was looking for a name that would give the idea of a “static” image without animation.

2025-01-10 05:08 UTC, alessandroboron commented on DuckDuckGo/PrivacyIconView.swift
> +    fileprivate var staticImage: UIImage? {
maybe static makes sense in this context, even the imageView was named staticImageView. Let me know if you can think of a better name

2025-01-10 05:14 UTC, alessandroboron commented on DuckDuckGo/TabViewController.swift
> +                                      malicousSiteThreatKind: specialErrorPageNavigationHandler.currentThreatKind,
Do you mind if I do this fix as a separate PR? I noticed it's an existing typo made in few different places. I will fix it in BSK and then make a PR for iOS and macOS.

2025-01-10 17:07 UTC, jaceklyp approved these changes

2025-01-14 03:25 UTC, merged