New Feature - quick sharing bookmark from bookmarks screen..
duckduckgo/iOS pull request #409
Opened 2019-02-16 00:32 UTC by pastmaster007

**Description**:
Ability to share a bookmark on swipe from left to right in bookmarks screen.
This feature supports only in iOS 11.0 and above.
Added corresponding new pixel identifier called "bm_sh" (bookmark share)

**Steps to test this PR**:
1. On iOS 11 and above supported device, open bookmarks screen by pressing bookmarks icon on home screen tab bar
1. Now swipe left to right on a bookmark results share sheet appears.

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2019-02-20 20:41 UTC, pastmaster007 commented
video to verify feature
https://vimeo.com/318577692

2019-02-22 12:44 UTC, bwaresiak requested changes
Thank you for making this PR. I've left some comments inline.

2019-02-22 12:44 UTC, bwaresiak commented on Core/Pixel.swift
> +    case bookmarkShare = "bm_sh"
You don't have to worry about pixel requests - these are needed only when we want to check feature usage after a release. It's OK to remove it from this and other PRs.

2019-02-22 12:44 UTC, bwaresiak commented on DuckDuckGo/BookmarksViewController.swift
> +        shareContextualAction.backgroundColor = UIColor.ppGreen
Please use 'cornflowerBlue' instead.

2019-02-22 12:44 UTC, bwaresiak commented on DuckDuckGo/BookmarksViewController.swift
> +        let shareContextualAction = UIContextualAction.init(style: .normal, title: "Share") { (_, _, completionHandler) in
Please drop the `.init`

2019-02-22 12:44 UTC, bwaresiak commented on DuckDuckGo/BookmarksViewController.swift
> +        return UISwipeActionsConfiguration.init(actions: [shareContextualAction])
Please drop the `.init`

2019-02-22 12:44 UTC, bwaresiak commented on DuckDuckGo/BookmarksViewController.swift
> +            Logger.log(text: "share action")
I believe we can remove that and only log error cases, rather than regular usage.

2019-03-07 12:02 UTC, bwaresiak approved these changes
This looks good!

Sorry it took me a while to get back to you. Thanks for your contribution!

2019-03-07 12:03 UTC, merged