customise fire button to preserve logins
duckduckgo/iOS pull request #557
Opened 2020-01-16 12:13 UTC by brindy

Task/Issue URL:
Tech Design URL:
CC:

**Description**:

**Steps to test this PR**:
1.
1.

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2020-02-03 14:17 UTC, tomasstrba requested changes
@brindy good job! This is really handy feature

There are just two things I found:
- preserveLoginsSettingsWhileForgetting is not used anywhere
- I found exception on iPad Air 2, iOS 12. Go to Settings > Keep Me Signed, Use edit to Clear all domains, Tap on ''Clear data & Sign Out

2020-02-03 14:17 UTC, tomasstrba commented on Core/PreserveLogins.swift
> +    public var prompted: Bool {
In cases like this UserDefault property wrapper could be helpful for us. We wouldn't repeat same code again and make it more compact. Maybe it is good candidate for LHF days.

2020-02-03 14:17 UTC, tomasstrba commented on Core/Pixel.swift
> +    case preserveLoginsSettingsWhileForgetting = "m_pl_s_f"
Should "preserveLoginsSettingsWhileForgetting" pixel be fired somewhere in code or did you forget to remove definition?

2020-02-03 14:58 UTC, brindy commented
Thanks @tomasstrba! 

I am getting some feedback from the product review as well so will ping you when I need another review. 

The property wrapper is a great idea - I'll see about adding that, then we can clean up a lot of code throughout the codebase at some point in the future.

Thanks for the heads up about the crash - will investigate, though I suspect product review changes will actually make that go away.  Will ping you soon.

2020-02-03 15:27 UTC, brindy commented on Core/PreserveLogins.swift
> +    public var prompted: Bool {
I had a quick look, but it makes testing quite difficult as we tend to inject a user defaults object in that has a known state.  Nice idea, but I think I need to ponder it more before putting it in.

2020-02-05 13:00 UTC, brindy commented
Hey @tomasstrba - I *think* that's it for copy.  We also decided to restrict this functionality to iOS 13 users, so have added another test for that.  Ready to review again when you get chance.  Thanks!

2020-02-05 22:21 UTC, tomasstrba commented
LGTM! Good job @brindy!

2020-02-06 00:19 UTC, brindy commented
Thanks @tomasstrba !

2020-02-06 00:19 UTC, merged