Restore WebVIew SessionStateData
duckduckgo/iOS pull request #815
Opened 2021-01-22 09:42 UTC by mallexxx

Task/Issue URL: https://app.asana.com/0/481882893211075/1199540714173897/f
Tech Design URL: https://app.asana.com/0/481882893211075/1199540714173897/f
CC: @brindy 

**Description**:
This PR contains the implementation of WebView browsing session restoration

**Steps to test this PR**:
1. Disable Clear Data on exit in App Preferences
2. Make some browsing, opening tabs
3. Close the App
4. Terminate the App
5. Reopen the App 

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPad

**OS Testing**:

* [ ] iOS 11
* [ ] iOS 12
* [ ] iOS 13
* [ ] iOS 14

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2021-01-22 14:07 UTC, brindy requested changes
Looks good, seems to work.  I downgraded back to develop to test if we have to roll back and that seemed OK too.  I also tested the fire button and fire proofing, all good there as well.

Just one minor change to make, no need to obfuscate the symbol name.

Thanks!

2021-01-22 14:07 UTC, brindy commented on DuckDuckGo/WebView.swift
> +    private static let essionStateData = "essionStateData"
Let's not obfuscate this.

2021-01-25 01:58 UTC, mallexxx commented on DuckDuckGo/WebView.swift
> +    private static let essionStateData = "essionStateData"
Done 👍

2021-01-25 11:25 UTC, THISISDINOSAUR commented
Posting here so we don't forget: We have an ASAP task we need to get out on iOS (https://app.asana.com/0/414235014887631/1199654549449490/f), so let's hold off on merging this until that's released

2021-02-03 21:05 UTC, Asavarkhul commented on DuckDuckGo/TabViewController.swift
> +    func attachWebView(configuration: WKWebViewConfiguration, sessionStateData: Data? = nil,
Hey 👋
Just a quick question, why putting a `nil` default value there? Because you wanted to avoid changes when no `sessionStateData` is injected?

2021-02-03 21:09 UTC, Asavarkhul commented on DuckDuckGo/TabViewController.swift
> +        } catch {}
Second quick question 😇
You don't want to inform the user that the restoration failed?

2021-02-13 18:15 UTC, brindy commented
Hey @mallexxx - we've heard that Apple are making these APIs public, so it doesn't seem worth testing the review process with this, so going to close it out.  Thanks!

2021-02-13 18:15 UTC, closed without merging