New Browsing Menu
duckduckgo/iOS pull request #857
Opened 2021-04-12 22:44 UTC by bwaresiak

Task/Issue URL: https://app.asana.com/0/856498667320406/1199661417922878
Tech Design URL: https://app.asana.com/0/856498667320406/1199971443872605
CC:

**Description**:
- Introduce new Menu.
- Change Home Screen buttons: swap Bookmarks and Tabs.
- When browsing:
  - Expose Share button on the Top Bar.
  - Move Menu button to Bottom Bar.
 - Introduce new Toast view with action button.

**Steps to test this PR**:

1. Full Menu UX & features test.
  - Sizing, layout, animations.
  - Test each functionality.
  - Home screen & Share buttons.
  - iPhone & iPad.
  - Older iOS versions for possible layout issues.
2. Test new Toast.
3. Add-favorites flow from widget.

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPad

**OS Testing**:

* [ ] iOS 11
* [ ] iOS 12
* [ ] iOS 13
* [ ] iOS 14

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

2021-04-13 21:02 UTC, brindy approved these changes
Generally looking good.  Tests well. Works great on iOS 11, iPad, etc.  All flows seem good.

A few comments inline, nothing major. 

Additionally, is it worth removing the word "Toast" from function/var names, especially now we have the "ActionMessage" which is a much nicer name?

Finally, I made some comments in the product review but assuming none of those end up changing the code, feel free to merge once the above comments are addressed.

2021-04-13 21:02 UTC, brindy commented on DuckDuckGo/BrowsingMenu/BrowsingMenuViewController.swift
> +// swiftlint:disable line_length
Seems unnecessary?

2021-04-13 21:02 UTC, brindy commented on DuckDuckGo/BrowsingMenu/BrowsingMenuViewController.swift
> +    func setHeaderEntires(_ entries: [BrowsingMenuEntry]) {
typo: `Entires` -> `Entries`

2021-04-13 21:02 UTC, brindy commented on DuckDuckGo/BrowsingMenu/BrowsingMenuViewController.swift
> +    func setMenuEntires(_ entries: [BrowsingMenuEntry]) {
typo again, at least it's consistent :)

2021-04-13 21:02 UTC, brindy commented on DuckDuckGo/BrowsingMenu/BrowsingMenuViewController.swift
> +    func setMenuEntires(_ entries: [BrowsingMenuEntry])
typo: `Entires` -> `Entries`

2021-04-13 21:02 UTC, brindy commented on DuckDuckGo/TabViewControllerBrowsingMenuExtension.swift
> +        var entires = [BrowsingMenuEntry]()
typo: `entires` -> `entries`

2021-04-14 11:19 UTC, bwaresiak commented on DuckDuckGo/BrowsingMenu/BrowsingMenuViewController.swift
> +// swiftlint:disable line_length
No, it's needed for guards :)

2021-04-15 11:39 UTC, bwaresiak commented
@brindy I made one fix to a scenario that Craig found:
1. Enable clear data, with remove tabs option after 5 min.
2. Leave the app, wait 5min.
3. Open any URL (default browser flow) - menu button was not visible.

2021-04-15 21:58 UTC, samsymons requested changes
This is such good work here, nice one @bwaresiak. I'm spending some time stress testing this and collecting feedback below:

---

* If you display the menu and then use Command+T to create a new tab while it is still visible, it breaks the layout

![new-tab-layout](https://user-images.githubusercontent.com/183774/114943532-f9026280-9dfa-11eb-8f14-fb2326f38bfd.png)

2021-04-16 13:34 UTC, bwaresiak commented
@samsymons Thanks!

> If you display the menu and then use Command+T to create a new tab while it is still visible, it breaks the layout

Fixed, along with `cmd+w` and `cmd+shift+[` scenarios.

> BrowsingMenuButton behaves strangely as an accessibility element. Likely it should be treated as .button accessibility element and hide its children from VoiceOver

But it is .button for me... but I've found that accessibility labels for Bookmark vs Menu states were broken, so I've fixed that. Can you retest?

2021-04-16 15:57 UTC, samsymons commented
@bwaresiak This looks good now. I was having a hard time navigating to the 4 buttons at the top with VoiceOver, but it's working now. 🎉

2021-04-16 15:59 UTC, samsymons approved these changes

2021-04-20 20:08 UTC, bwaresiak commented
Thank you @samsymons  and @brindy

2021-04-20 20:08 UTC, merged