Remove unnecessary content offset for a webview when keyboard is displayed.
duckduckgo/iOS pull request #885
Opened 2021-05-18 22:26 UTC by untalfranfernandez

Task/Issue URL: https://github.com/duckduckgo/iOS/issues/847
Tech Design URL: 
CC:

**Description**:

There is an unnecessary bottom space added to any webview when the keyboard is displayed due to any textfield getting focused.

**Steps to test this PR**:
1. Open `https://nos.nl/zoeken`
2. Tap on the main textfield available.
3. Scroll the webview to the bottom.

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [x] Portrait
* [x] Landscape

**Device Testing**:

* [x] iPhone SE (1st Gen)
* [x ] iPhone 8
* [x] iPhone X
* [x] iPad

**OS Testing**:

* [ ] iOS 13
* [x] iOS 14

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

2021-05-19 15:03 UTC, brindy requested changes
Hi - thanks for this, but it doesn't seem to work well with find in page.  On the page you suggested if you open find in page and search for NOS you can't see the items under the find in page UI / keyboard.   Any ideas?

2021-05-24 19:28 UTC, untalfranfernandez commented
Hi @brindy I came up with an improved solution that works on that scenario you've described.

Now, the container has a vertical spacing constraint with the find-in-page view, so the size for the container gets automatically reduced when this view is shown. 

<img width="305" alt="Screen Shot 2021-05-24 at 19 50 35" src="https://user-images.githubusercontent.com/834463/119397338-45806e00-bcd6-11eb-9880-08800d942619.png">

There is one scenario pending to review, which was failing previously and now is mitigated but far from being fixed: 
If you trigger the "find-in-page" feature and without dismissing it, tap on any textfield in the website display, there is a mismatch between the sizes of `WKContentView` and the `WKScrollView`

I have some ideas about how to fix this, but those imply more deeper changes that could be discussed in another PR.

2021-06-04 10:17 UTC, brindy commented
Hi - sorry for the delay in reply and thanks for sticking with this. 

I've had a think about this, and I don't want us to head in this direction because we have a bug related to resizing the web views.   You may have noticed that some pages change when the bars appear / disappear and also that the previous page's position is lost when you go back, this is all due to resizing the web view.

I think approach would likely compound that problem making it harder for us to do a fix in the future.  

I think in fact that we need to solve the web view resizing problem first before addressing the problem this PR fixes. 

Any thoughts on that?

Thanks

2021-06-08 07:50 UTC, untalfranfernandez commented
Hey, I do agree with you on that, so, we can close this PR and maybe give it another go at any given point in future.

2021-06-19 14:24 UTC, brindy commented
Thanks @untalfranfernandez !

2021-06-19 14:24 UTC, closed without merging