Support JS prompts
duckduckgo/iOS pull request #980
Opened 2021-10-12 18:16 UTC by Bunn

Task/Issue URL: https://app.asana.com/0/1201011656765697/1200632147004921
Tech Design URL:
CC:

**Description**:
Add support for JS alerts/confirm and text modals.

**Steps to test this PR**:
1. Check the html file in the asana ticket to help you trigger those alerts 
2. Tap on each button to make sure the alerts (and callbacks) are being called correctly 

**Device Testing**:

* [X] iPhone SE (1st Gen)
* [X] iPhone 11
* [X] iPad Pro

**OS Testing**:

* [X] iOS 14
* [X] iOS 15

**Theme Testing**:

* [X] Light theme
* [X] Dark theme

2021-10-12 19:11 UTC, bwaresiak requested changes
Great job, works as expected. 👍 I've left few comments inline for some minor things I've found.

2021-10-12 19:11 UTC, bwaresiak commented on DuckDuckGo/en.lproj/Localizable.strings
> +"webJSAlert.OK.button" = "OK";
Maybe it would be good to request translations and update these? There strings should be already in translation memory, ping me if needed. :)

2021-10-12 19:11 UTC, bwaresiak commented on DuckDuckGo/WebJSAlert.swift
> +                if let text = alertController.textFields?.first?.text {
Doesn't this create reference loop?

2021-10-12 19:11 UTC, bwaresiak commented on DuckDuckGo/WebJSAlert.swift
> +            let alertController = UIAlertController(title: nil, message: message, preferredStyle: .alert)
This seems to be duplicated.

2021-10-12 19:11 UTC, bwaresiak commented on DuckDuckGo/UserText.swift
> +    public static let webJSAlertCancelButton = NSLocalizedString("webJSAlert.cancel.button", value: "Cancel", comment: "Cancel button for JavaScript alerts")
Glad to see proper comments 😄

2021-10-12 19:32 UTC, Bunn commented on DuckDuckGo/WebJSAlert.swift
> +                if let text = alertController.textFields?.first?.text {
Yes.. it does 🥲

2021-10-14 14:44 UTC, Bunn commented
@bwaresiak I've done the requested changes, just waiting to sync up on the translation thing. 
Once it's done I'll re-request review.

2021-10-15 08:52 UTC, Bunn commented on DuckDuckGo/en.lproj/Localizable.strings
> +"webJSAlert.OK.button" = "OK";
As discussed, these will be taken care on another PR.

2021-10-15 09:50 UTC, bwaresiak approved these changes
LGTM 👍

2021-10-15 14:44 UTC, merged