Rewrite Tracking Links (AMP Phase)
duckduckgo/iOS pull request #994
Opened 2021-11-04 14:18 UTC by SlayterDev

Task/Issue URL: https://app.asana.com/0/72649045549333/1201286795398788/f
Tech Design URL: https://app.asana.com/0/481882893211075/1201299313936485/f
CC: @bwaresiak 

**Description**:
This PR adds support for extracting the canonical URL from AMP links

**Steps to test this PR**:
1. TBD
2.

**Copy Testing**:

* [ ] Use of correct apostrophes in new copy, ie `’` rather than `'`

**Orientation Testing**:

* [ ] Portrait
* [ ] Landscape

**Device Testing**:

* [ ] iPhone SE (1st Gen)
* [ ] iPhone 8
* [ ] iPhone X
* [ ] iPad

**OS Testing**:

* [ ] iOS 13
* [ ] iOS 14
* [ ] iOS 15

**Theme Testing**:

* [ ] Light theme
* [ ] Dark theme

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
**When ready for review, remember to post the PR in MM**

2021-11-18 14:09 UTC, bwaresiak requested changes

2021-11-18 14:09 UTC, bwaresiak commented on Core/AMPCanonicalExtractor.swift
> +        self.completion = completion
This could cause a race condition as instance is reused between tabs now.

2021-11-18 14:09 UTC, bwaresiak commented on Core/AMPCanonicalExtractor.swift
> +    public static let shared = AMPCanonicalExtractor()
We could move it to TabVC and have it as a property there, so lifetime and state is encapsulated and "connected" to state of the Tab itself.

2021-11-18 14:09 UTC, bwaresiak commented on DuckDuckGo/BrokenSiteInfo.swift
> +                          Keys.ampUrl: LinkCleaner.shared.getLastAmpUrl() ?? ""]
We could pass AMP state as a init parameter to avoid having that as a singleton.

2021-11-19 12:42 UTC, bwaresiak commented on Core/AMPCanonicalExtractor.swift
> +        webView?.load(URLRequest(url: url))
What about completion handler in case connection times out and URL is not loaded?

2021-11-19 12:43 UTC, bwaresiak commented on Core/AMPCanonicalExtractor.swift
> +            self?.imageBlockingRules = ruleList
We could try to query for precompiled rules before compiling from scratch.

2021-11-19 12:44 UTC, bwaresiak commented on Core/AMPCanonicalExtractor.swift
> +                print(error?.localizedDescription ?? "AMPCanonicalExtractor - Error compiling image blocking rules")
This should be firing a debug pixel so we know if things are not working.

2021-11-19 12:45 UTC, bwaresiak commented on DuckDuckGo/TabViewController.swift
> +    private var ampExtractor: AMPCanonicalExtractor?
Can these be non-optional?

2021-11-19 12:48 UTC, bwaresiak commented
Thanks, this looks much better when embedded in TabViewController. I've dropped in few more comments after looking at this more carefully. Also tets are not passing, but it looks it's because of linter warnings 

    BrokenSiteInfo.swift:49:1: Line Length Violation: Line should be 150 characters or less: currently 164 characters (line_length)

2021-11-19 14:52 UTC, SlayterDev commented
> Thanks, this looks much better when embedded in TabViewController. I've dropped in few more comments after looking at this more carefully. Also tets are not passing, but it looks it's because of linter warnings
> 
> ```
> BrokenSiteInfo.swift:49:1: Line Length Violation: Line should be 150 characters or less: currently 164 characters (line_length)
> ```

Swore I pushed that fix

2021-11-24 12:52 UTC, bwaresiak requested changes
I gave this pretty thorough tests - some comments inline.

Other than that, I have few more questions:

1/ On navigation to AMP page:

1. We have current domain as unprotected and navigate to AMP webpage -> AMP version is loaded.
2. Any tap on a link on the AMP webpage will then navigate to actual site instead of amp. 

Is that expected? Was this discussed somewhere?

2/ On allow-listing google.com

User may by accident allow list `google.com` if they turn off protections on AMP site that is hosted on `google.com` - have we discussed the implications somewhere?

3/ Long pressing the link shows preview and connects with the AMP site - I guess this is a bug?

3/ Long pressing the link and opening in new tab navigates to AMP webpage - bug?

2021-11-24 12:52 UTC, bwaresiak commented on Core/LinkCleaner.swift
> +    }
Maybe instead of having these 3 functions, just make lastAmpUrl var public?

2021-11-24 12:52 UTC, bwaresiak commented on Core/LinkCleaner.swift
> +                                            config: PrivacyConfiguration = PrivacyConfigurationManager.shared.privacyConfig) -> URL? {
We need to make it resistant to race conditions, as it is possible for user to invoke this by clicking on a link, then tap on another link. There are at least 3 scenarios:

1. Amp Link into Amp Link - so when this is called more than once in succession. We need to cancel "old" extraction and ensure no callbacks are made.
2. Regular link into Amp Link - I'd guess this is not a big problem.
3. Amp Link into Regular link - we would need to cancel the extraction to ensure no callback is made.

2021-11-24 12:52 UTC, bwaresiak commented on Core/Pixel.swift
> +    case ampBlockingRulesCompilationFailed = "m_d_amp_rules_compilation_failed"
Let's do `m_debug_....` fo clarity :)

2021-11-24 12:52 UTC, bwaresiak commented on DuckDuckGo/TabViewController.swift
> +            ampExtractor.getCanonicalUrl(initiator: nil, url: url) { canonical in
UX of waiting for this to finish is poor, especially on first load - I'd add `showProgressIndicator()` above this line (and in the code below that calls this) to give some visual indicator that things are happening.

2021-11-24 12:52 UTC, bwaresiak commented on DuckDuckGo/TabViewController.swift
> +            ampExtractor.getCanonicalUrl(initiator: webView.url,
Please add `showProgressIndicator()` above this.

2021-11-24 12:52 UTC, bwaresiak commented on DuckDuckGo/TabViewController.swift
> +            ampExtractor.getCanonicalUrl(initiator: nil, url: url) { canonical in
And maybe add comment in both places that we do this to improve UX.

2021-11-29 16:54 UTC, SlayterDev commented
@bwaresiak  I've addressed your comments.

1/ This is expected as AMP only applies to the destination link. The site itself handles all other content (when clicking other links etc.).

2/ This is expected but if you have concerns we can take this one to Asana

3/ Fixed.

4/ Fixed/

2021-12-01 12:39 UTC, bwaresiak approved these changes
Great job @SlayterDev!

2021-12-01 15:04 UTC, merged